### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by kunlong-luo** [Aalia98/Vedio-Player#1]
Hello, I want to ask for your help, how to load the picture onto the page?

**Comment by Aalia98** [comment]
Images can't be loaded.....only video is loaded

**Comment by kunlong-luo** [comment]
> Images can't be loaded.....only video is loaded

Thank you very much, I think I have solved this problem, your code is very well written, I like this style.

**Comment by kunlong-luo** [comment]
> Images can't be loaded.....only video is loaded
